[package]
name = "wasnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"
libm = "0.2.6"
smallvec = { version = "1.10.0", features = ["union", "const_generics", "const_new"] }
wasm-bindgen = "0.2.83"

[dev-dependencies]
png = "0.17.6"
serde_json = "1.0.91"

[lib]
crate-type = ["lib", "cdylib"]
