[workspace]
members = [
  ".",
  "wasnn-cli",
  "wasnn-examples",
  "wasnn-imageio",
  "wasnn-imageproc",
  "wasnn-ocr",
  "wasnn-ocr-cli",
  "wasnn-tensor",
  "wasnn-text"
]
default-members = [
  ".",
  "wasnn-imageproc",
  "wasnn-tensor",
  "wasnn-text"
]

[package]
name = "wasnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"
libm = "0.2.6"
rayon = "1.7.0"
smallvec = { version = "1.10.0", features = ["union", "const_generics", "const_new"] }
wasnn-tensor = { path = "./wasnn-tensor" }
wasnn-vecmath = { path = "./wasnn-vecmath" }

[dev-dependencies]
serde_json = "1.0.91"

[lib]
crate-type = ["lib", "cdylib"]

[features]
# Use AVX-512 instructions if available. Requires nightly Rust for AVX-512 intrinsics.
avx512 = []
# Generate WebAssembly API using wasm-bindgen.
wasm_api = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"

[lints.clippy]
# `assert!(const)` effectively used as a static assert, which compiler will
# optimize away.
assertions_on_constants = "allow"
# Clippy frequently suggests to replace for loops with const bounds (often used
# in performance-critical loops) with iterators, which is more verbose and
# potentially less efficient.
needless_range_loop = "allow"
too_many_arguments = "allow"
