[package]
name = "wasnn"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.1.2"
wasm-bindgen = "0.2.83"

[dev-dependencies]
png = "0.17.6"

[lib]
crate-type = ["lib", "cdylib"]
