[workspace]
members = [
  "wasnn-imageio",
  "wasnn-imageproc",
  "wasnn-ocr",
  "wasnn-ocr-cli",
  "wasnn-tensor"
]

[package]
name = "wasnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"
libm = "0.2.6"
rayon = "1.7.0"
smallvec = { version = "1.10.0", features = ["union", "const_generics", "const_new"] }
wasm-bindgen = "0.2.83"
wasnn-tensor = { path = "./wasnn-tensor" }
wasnn-vecmath = { path = "./wasnn-vecmath" }

[dev-dependencies]
hound = "3.5.1"
image = { version = "0.24.6", default-features = false, features = ["png", "jpeg", "webp"] }
lexopt = "0.3.0"
png = "0.17.6"
serde_json = "1.0.91"
wasnn-imageio = { path = "./wasnn-imageio" }
wasnn-imageproc = { path = "./wasnn-imageproc" }
wasnn-ocr = { path = "./wasnn-ocr" }

[lib]
crate-type = ["lib", "cdylib"]

[features]
wasm_api = []
