[package]
name = "wasnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "22.10.26"
libm = "0.2.6"
rayon = "1.7.0"
smallvec = { version = "1.10.0", features = ["union", "const_generics", "const_new"] }
wasm-bindgen = "0.2.83"

[dev-dependencies]
fastrand = "1.9.0"
image = { version = "0.24.6", default-features = false, features = ["png", "jpeg", "webp"] }
png = "0.17.6"
serde_json = "1.0.91"

[lib]
crate-type = ["lib", "cdylib"]
