[package]
name = "rten-vecmath"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
fastrand = "1.9.0"
libm = "0.2.6"

[lib]
crate-type = ["lib"]

[lints.clippy]
# See comments about `needless_range_loop` in root Cargo.toml.
needless_range_loop = "allow"
manual_memcpy = "allow"
