[package]
name = "ocrs-cli"
version = "0.1.0"
edition = "2021"
authors = ["Robert Knight"]
description = "OCR CLI tool for extracting text from images"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/robertknight/rten"
repository = "https://github.com/robertknight/rten"

[dependencies]
image = { version = "0.24.6", default-features = false, features = ["png", "jpeg", "jpeg_rayon", "webp"] }
png = "0.17.6"
serde_json = "1.0.91"
rten = { path = "../", version = "0.1.0" }
rten-imageproc = { path = "../rten-imageproc", version = "0.1.0" }
rten-tensor = { path = "../rten-tensor", version = "0.1.0" }
ocrs = { path = "../ocrs", version = "0.1.0" }
lexopt = "0.3.0"
ureq = "2.7.1"
url = "2.4.0"

[[bin]]
name = "ocrs"
path = "src/main.rs"
