[package]
name = "ocrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.7.0"
rten = { path = "../" }
rten-imageproc = { path = "../rten-imageproc" }
rten-tensor = { path = "../rten-tensor" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.87"

[dev-dependencies]
fastrand = "1.9.0"

[lib]
crate-type = ["lib", "cdylib"]
