[package]
name = "rten-imageio"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.6", default-features = false, features = ["png", "jpeg", "jpeg_rayon", "webp"] }
png = "0.17.6"
rten-tensor = { path = "../rten-tensor" }
