[package]
name = "wasnn-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.9.0"
wasnn = { path = "../" }
wasnn-tensor = { path = "../wasnn-tensor" }
lexopt = "0.3.0"

[[bin]]
name = "wasnn"
path = "src/main.rs"
