[package]
name = "rten-cli"
version = "0.5.0"
edition = "2021"
authors = ["Robert Knight"]
description = "CLI tool for inspecting and running RTen models"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/robertknight/rten"
repository = "https://github.com/robertknight/rten"

[dependencies]
fastrand = "2.0.2"
rten = { path = "../", version = "0.5.0", features=["random"] }
rten-tensor = { path = "../rten-tensor", version = "0.4.0" }
lexopt = "0.3.0"

[[bin]]
name = "rten"
path = "src/main.rs"
