[package]
name = "rten-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.9.0"
rten = { path = "../" }
rten-tensor = { path = "../rten-tensor" }
lexopt = "0.3.0"

[[bin]]
name = "rten"
path = "src/main.rs"
