name: CI
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup rust
      run: rustup target add wasm32-unknown-unknown
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install wasm-bindgen
      run: which wasm-bindgen || cargo install wasm-bindgen-cli
    - name: Build
      run: cargo build
    - name: WASM build
      run: make wasm
    - name: Test
      run: make test
    - name: Lint
      run: |
        make checkformatting
        make lint
